### ISSUE TITLE
NBT data

### ISSUE THREAD

**Issue by 9NONAGON** [d0sboots/Minecraft#1]
Hello,

I know this is the wrong place to put this, but I saw you were the only active one on the pthon NBT repo.
I don't mean to bother you, but I've been trying for days to save an .mca file after modifying it. I don't know how much you've contributed to it, but I don't understand why there is a full interface for modifying RegionFile objects, but not writing them to files.

Is there any way you could help? If not that's fine.

Best,
nog

**Comment by d0sboots** [comment]
![image](https://user-images.githubusercontent.com/459704/209418341-35383263-b3e7-45be-bd66-9b463f1bff8f.png)

I haven't touched this stuff in a decade, sorry.

**Comment by 9NONAGON** [comment]
Yes
